apiVersion: v1
kind: Service
metadata:
  name: transaction-service-port
  namespace: ledger
spec:
  selector:
    app: transactions-service
  ports:
    - protocol: TCP
      port: 4001 # Port exposed by the service
  type: LoadBalancer  # Set the service type to LoadBalancer
      
