apiVersion: v1
kind: Service
metadata:
  name: user-service-port
  namespace: ledger
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 4000  # Port exposed by the service
