apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-service-deployment
  namespace: ledger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactions-service
  template:
    metadata:
      labels:
        app: transactions-service
    spec:
      containers:
      - name: transactions-service-container
        image: alazcano255/transactions-service:v0.1
        ports:
        - containerPort: 4001
        env:
          - name: MONGO_URL
            value: "mongodb://host.docker.internal:27017/"
          - name: PORT
            value: "4001"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
        # Add additional environment variables here
        # Add additional container configuration here, such as volume mounts, readiness and liveness probes, etc.
